#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36323
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Rapidware.Financier.Finance.UI.Android.Resource", IsApplication=false)]

namespace Rapidware.Financier.Finance.UI.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public static int calculatorButtonStyle = 2130771975;
			
			// aapt resource value: 0x7f010008
			public static int calculatorRowStyle = 2130771976;
			
			// aapt resource value: 0x7f010003
			public static int completePickerStyle = 2130771971;
			
			// aapt resource value: 0x7f010005
			public static int fieldNameStyle = 2130771973;
			
			// aapt resource value: 0x7f010006
			public static int horizontalDividerStyle = 2130771974;
			
			// aapt resource value: 0x7f010001
			public static int incompletePickerStyle = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int invalidPickerStyle = 2130771970;
			
			// aapt resource value: 0x7f010004
			public static int pickerButtonStyle = 2130771972;
			
			// aapt resource value: 0x7f010000
			public static int pickerStyle = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040002
			public static int calculator_all_clear = 2130968578;
			
			// aapt resource value: 0x7f040012
			public static int calculator_cancel = 2130968594;
			
			// aapt resource value: 0x7f040003
			public static int calculator_clear = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public static int calculator_divide = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public static int calculator_eight = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public static int calculator_equals = 2130968591;
			
			// aapt resource value: 0x7f040009
			public static int calculator_five = 2130968585;
			
			// aapt resource value: 0x7f040008
			public static int calculator_four = 2130968584;
			
			// aapt resource value: 0x7f040000
			public static int calculator_minus = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public static int calculator_nine = 2130968590;
			
			// aapt resource value: 0x7f040004
			public static int calculator_one = 2130968580;
			
			// aapt resource value: 0x7f040010
			public static int calculator_period = 2130968592;
			
			// aapt resource value: 0x7f040001
			public static int calculator_plus = 2130968577;
			
			// aapt resource value: 0x7f040013
			public static int calculator_set = 2130968595;
			
			// aapt resource value: 0x7f04000c
			public static int calculator_seven = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public static int calculator_six = 2130968586;
			
			// aapt resource value: 0x7f040006
			public static int calculator_three = 2130968582;
			
			// aapt resource value: 0x7f040007
			public static int calculator_times = 2130968583;
			
			// aapt resource value: 0x7f040005
			public static int calculator_two = 2130968581;
			
			// aapt resource value: 0x7f040011
			public static int calculator_zero = 2130968593;
			
			// aapt resource value: 0x7f040015
			public static int solver_number_complete_picker_value = 2130968597;
			
			// aapt resource value: 0x7f040016
			public static int solver_number_incomplete_picker_value = 2130968598;
			
			// aapt resource value: 0x7f040017
			public static int solver_number_invalid_picker_value = 2130968599;
			
			// aapt resource value: 0x7f040018
			public static int solver_number_picker_button = 2130968600;
			
			// aapt resource value: 0x7f040014
			public static int solver_number_picker_field = 2130968596;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int calculator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int labelled_number_picker = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030002
			public static int calculator_all_clear_text = 2130903042;
			
			// aapt resource value: 0x7f030013
			public static int calculator_cancel_text = 2130903059;
			
			// aapt resource value: 0x7f030003
			public static int calculator_clear_text = 2130903043;
			
			// aapt resource value: 0x7f03000b
			public static int calculator_divide_text = 2130903051;
			
			// aapt resource value: 0x7f03000d
			public static int calculator_eight_text = 2130903053;
			
			// aapt resource value: 0x7f03000f
			public static int calculator_equals_text = 2130903055;
			
			// aapt resource value: 0x7f030009
			public static int calculator_five_text = 2130903049;
			
			// aapt resource value: 0x7f030008
			public static int calculator_four_text = 2130903048;
			
			// aapt resource value: 0x7f030000
			public static int calculator_minus_text = 2130903040;
			
			// aapt resource value: 0x7f03000e
			public static int calculator_nine_text = 2130903054;
			
			// aapt resource value: 0x7f030004
			public static int calculator_one_text = 2130903044;
			
			// aapt resource value: 0x7f030010
			public static int calculator_period_text = 2130903056;
			
			// aapt resource value: 0x7f030001
			public static int calculator_plus_text = 2130903041;
			
			// aapt resource value: 0x7f030012
			public static int calculator_set_text = 2130903058;
			
			// aapt resource value: 0x7f03000c
			public static int calculator_seven_text = 2130903052;
			
			// aapt resource value: 0x7f03000a
			public static int calculator_six_text = 2130903050;
			
			// aapt resource value: 0x7f030006
			public static int calculator_three_text = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int calculator_times_text = 2130903047;
			
			// aapt resource value: 0x7f030005
			public static int calculator_two_text = 2130903045;
			
			// aapt resource value: 0x7f030011
			public static int calculator_zero_text = 2130903057;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
